
import { Language, Profile, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
    so: {
        politics: 'Siyaasadda',
        business: 'Ganacsiga',
        login: 'Gal',
        logout: 'Ka Bax',
        heroTag: 'Kaydka Rasmiga ah ee Qaranka',
        heroTitle1: 'Kaydka Rasmiga ah ee',
        heroTitle2: 'Qaranka Soomaaliyeed',
        heroSub: 'Hel xogta siyaasiyiinta, ganacsiga, iyo taariikhda dalka laga soo bilaabo 1960 ilaa 2025.',
        searchPlaceholder: 'Raadi Siyaasi ama Shirkad...',
        liveStats: 'Xogta Tooska ah',
        updatedNow: 'Hadda la cusbooneysiiyay',
        totalEntries: 'Wadarta Diiwaanka',
        verified: 'La Hubiyay',
        politician: 'Siyaasi',
        politicianDesc: 'Hogaamiyaasha & Xildhibaanada',
        politicianDescFull: 'Hogaamiyaasha & Xildhibaanada',
        businessDesc: 'Shirkadaha & Maamulayaasha',
        businessDescFull: 'Shirkadaha & Maamulayaasha',
        politicsDirectory: 'Diiwaanka Siyaasadda',
        businessDirectory: 'Diiwaanka Ganacsiga',
        searchResults: 'Natiijada Raadinta',
        showing: 'Waxaa lasoo saaray',
        results: 'natiijo',
        clearSearch: 'Tirtir Raadinta',
        viewDetails: 'Faahfaahin',
        noResults: 'Lama helin wax u dhigma',
        latestInsights: 'Xogaha Cusub',
        viewAll: 'Eeg Dhamaan',
        trendingNow: 'Kuwa ugu hadal-haynta badan',
        fame: 'Caan-ah',
        popularity: 'Taageero',
        tabOverview: 'Guudmar',
        tabBio: 'Taariikh',
        tabWork: 'Shaqo',
        tabArchive: 'Kayd',
        summary: 'Kooban',
        coreServices: 'Adeegyada Muhiimka ah',
        verificationStatus: 'Heerka Hubinta',
        verifiedMsg: 'Profile-kan waxaa hubiyay gudiga madaxa-banaan ee DIIWAAN.',
        earlyLife: 'Bilowgii Nolosha & Waxbarashada',
        bioPlaceholder: 'Halkan waxaa kasoo muuqan doona taariikh nololeedka oo faahfaahsan.',
        influenceScore: 'Heerka Saamaynta',
        share: 'La wadaag',
        linkCopied: 'Xiriirinta waa la koobiyey',
        shareProfile: 'La wadaag Profile-ka',
        copyLink: 'Nuqul Xiriirinta',
        shareVia: 'La wadaag...',
        edit: 'Wax ka bedel',
        save: 'Keydi',
        cancel: 'Jooji',
        editProfile: 'Wax ka bedel Profile-ka',
        imageUrl: 'Xiriirinta Sawirka',
        name: 'Magaca',
        role: 'Xilka',
        location: 'Goobta',
        bio: 'Taariikhda',
        category: 'Qeybta',
        addProfile: 'Ku dar Profile Cusub',
        deleteProfile: 'Tirtir Profile-ka',
        confirmDelete: 'Ma hubtaa inaad tirtirto profile-kan?',
        adminAccess: 'Maamule: Waa lagusoo dhaweeyay',
        adminLogout: 'Si guul leh ayaad uga baxday',
        articleRead: 'Akhri Qoraalka',
        close: 'Xir'
    },
    en: {
        politics: 'Politics',
        business: 'Business',
        login: 'Login',
        logout: 'Logout',
        heroTag: 'National Official Archive',
        heroTitle1: 'Official Archive of the',
        heroTitle2: 'Somali Nation',
        heroSub: 'Find data on politicians, business leaders, and national history from 1960 to 2025.',
        searchPlaceholder: 'Search Politician or Company...',
        liveStats: 'Live Statistics',
        updatedNow: 'Updated just now',
        totalEntries: 'Total Entries',
        verified: 'Verified',
        politician: 'Politician',
        politicianDesc: 'Leaders & MPs',
        politicianDescFull: 'Leaders & MPs',
        businessDesc: 'Companies & CEOs',
        businessDescFull: 'Companies & CEOs',
        politicsDirectory: 'Politicians Directory',
        businessDirectory: 'Business Directory',
        searchResults: 'Search Results',
        showing: 'Showing',
        results: 'results',
        clearSearch: 'Clear Search',
        viewDetails: 'View Details',
        noResults: 'No results found matching',
        latestInsights: 'Latest Insights',
        viewAll: 'View All',
        trendingNow: 'Trending Now',
        fame: 'Fame',
        popularity: 'Popularity',
        tabOverview: 'Overview',
        tabBio: 'Biography',
        tabWork: 'Work History',
        tabArchive: 'Archive',
        summary: 'Summary',
        coreServices: 'Core Services',
        verificationStatus: 'Verification Status',
        verifiedMsg: 'This profile has been verified by the DIIWAAN independent committee.',
        earlyLife: 'Early Life & Education',
        bioPlaceholder: 'Detailed biography content will appear here.',
        influenceScore: 'Influence Score',
        share: 'Share',
        linkCopied: 'Link copied',
        shareProfile: 'Share Profile',
        copyLink: 'Copy Link',
        shareVia: 'Share via...',
        edit: 'Edit',
        save: 'Save',
        cancel: 'Cancel',
        editProfile: 'Edit Profile',
        imageUrl: 'Image URL',
        name: 'Name',
        role: 'Role',
        location: 'Location',
        bio: 'Biography',
        category: 'Category',
        addProfile: 'Add New Profile',
        deleteProfile: 'Delete Profile',
        confirmDelete: 'Are you sure you want to delete this profile?',
        adminAccess: 'Admin Access Granted',
        adminLogout: 'Logged out successfully',
        articleRead: 'Read Article',
        close: 'Close'
    },
    ar: {
        politics: 'السياسة',
        business: 'الأعمال',
        login: 'دخول',
        logout: 'خروج',
        heroTag: 'الأرشيف الوطني الرسمي',
        heroTitle1: 'الأرشيف الرسمي',
        heroTitle2: 'للأمة الصومالية',
        heroSub: 'اعثر على بيانات السياسيين ورجال الأعمال وتاريخ الوطن من 1960 إلى 2025.',
        searchPlaceholder: 'ابحث عن سياسي أو شركة...',
        liveStats: 'إحصائيات مباشرة',
        updatedNow: 'تم التحديث للتو',
        totalEntries: 'إجمالي المدخلات',
        verified: 'مؤكد',
        politician: 'سياسي',
        politicianDesc: 'القادة والنواب',
        politicianDescFull: 'القادة والنواب',
        businessDesc: 'الشركات والمدراء',
        businessDescFull: 'الشركات والمدراء',
        politicsDirectory: 'دليل السياسيين',
        businessDirectory: 'دليل الشركات',
        searchResults: 'نتائج البحث',
        showing: 'عرض',
        results: 'نتائج',
        clearSearch: 'مسح البحث',
        viewDetails: 'عرض التفاصيل',
        noResults: 'لم يتم العثور على نتائج لـ',
        latestInsights: 'أحدث الرؤى',
        viewAll: 'عرض الكل',
        trendingNow: 'الأكثر تداولاً',
        fame: 'الشهرة',
        popularity: 'الشعبية',
        tabOverview: 'نظرة عامة',
        tabBio: 'السيرة',
        tabWork: 'العمل',
        tabArchive: 'الأرشيف',
        summary: 'ملخص',
        coreServices: 'الخدمات الأساسية',
        verificationStatus: 'حالة التحقق',
        verifiedMsg: 'تم التحقق من هذا الملف الشخصي بواسطة لجنة ديوان المستقلة.',
        earlyLife: 'النشأة والتعليم',
        bioPlaceholder: 'سيظهر محتوى السيرة الذاتية المفصل هنا.',
        influenceScore: 'درجة التأثير',
        share: 'شارك',
        linkCopied: 'تم نسخ الرابط',
        shareProfile: 'مشاركة الملف الشخصي',
        copyLink: 'نسخ الرابط',
        shareVia: 'شارك عبر...',
        edit: 'تعديل',
        save: 'حفظ',
        cancel: 'إلغاء',
        editProfile: 'تعديل الملف الشخصي',
        imageUrl: 'رابط الصورة',
        name: 'الاسم',
        role: 'المنصب',
        location: 'الموقع',
        bio: 'السيرة الذاتية',
        category: 'الفئة',
        addProfile: 'إضافة ملف جديد',
        deleteProfile: 'حذف الملف الشخصي',
        confirmDelete: 'هل أنت متأكد أنك تريد حذف هذا الملف؟',
        adminAccess: 'تم منح صلاحيات المسؤول',
        adminLogout: 'تم تسجيل الخروج بنجاح',
        articleRead: 'اقرأ المقال',
        close: 'إغلاق'
    }
};

export const PROFILES: Profile[] = [
    {
        id: 1,
        name: { so: 'Xasan Sheekh Maxamuud', en: 'Hassan Sheikh Mohamud', ar: 'حسن شيخ محمود' },
        role: { so: 'Madaxweynaha JFS', en: 'President of Somalia', ar: 'رئيس الصومال' },
        location: { so: 'Muqdisho', en: 'Mogadishu', ar: 'مقديشو' },
        category: 'Politician',
        verified: true,
        image: 'https://picsum.photos/id/1012/200/200',
        bio: { so: 'Madaxweynaha Jamhuuriyadda Federaalka Soomaaliya.', en: 'President of the Federal Republic of Somalia.', ar: 'رئيس جمهورية الصومال الفيدرالية.' },
        ratings: { fame: 92, popularity: 85 }
    },
    {
        id: 2,
        name: { so: 'Maxamed C/laahi Farmaajo', en: 'Mohamed Abdullahi Farmaajo', ar: 'محمد عبد الله فرماجو' },
        role: { so: 'Madaxweynihii Hore', en: 'Former President', ar: 'الرئيس السابق' },
        location: { so: 'Muqdisho', en: 'Mogadishu', ar: 'مقديشو' },
        category: 'Politician',
        verified: true,
        image: 'https://picsum.photos/id/1025/200/200',
        bio: { so: 'Madaxweynihii 9aad ee Soomaaliya.', en: '9th President of Somalia.', ar: 'الرئيس التاسع للصومال.' },
        ratings: { fame: 90, popularity: 88 }
    },
    {
        id: 3,
        name: { so: 'Xasan Cali Khayre', en: 'Hassan Ali Khaire', ar: 'حسن علي خيري' },
        role: { so: 'Ra’iisul Wasaarihii Hore', en: 'Former Prime Minister', ar: 'رئيس الوزراء السابق' },
        location: { so: 'Muqdisho', en: 'Mogadishu', ar: 'مقديشو' },
        category: 'Politician',
        verified: true,
        image: 'https://picsum.photos/id/1005/200/200',
        bio: { so: 'Musharax madaxweyne iyo ra\'iisul wasaarihii hore.', en: 'Presidential candidate and former PM.', ar: 'مرشح رئاسي ورئيس وزراء سابق.' },
        ratings: { fame: 85, popularity: 70 }
    },
    {
        id: 4,
        name: { so: 'Siciid Cabdullaahi Deni', en: 'Said Abdullahi Deni', ar: 'سعيد عبد الله دني' },
        role: { so: 'Madaxweynaha Puntland', en: 'President of Puntland', ar: 'رئيس بونت لاند' },
        location: { so: 'Garoowe', en: 'Garowe', ar: 'غروي' },
        category: 'Politician',
        verified: true,
        image: 'https://picsum.photos/id/1011/200/200',
        bio: { so: 'Hogaamiyaha Puntland tan iyo 2019.', en: 'Leader of Puntland since 2019.', ar: 'زعيم بونت لاند منذ 2019.' },
        ratings: { fame: 80, popularity: 65 }
    },
    {
        id: 5,
        name: { so: 'Axmed Maxamed Islaam (Madoobe)', en: 'Ahmed Madobe', ar: 'أحمد مدوبي' },
        role: { so: 'Madaxweynaha Jubbaland', en: 'President of Jubaland', ar: 'رئيس جوبالاند' },
        location: { so: 'Kismaayo', en: 'Kismayo', ar: 'كسمايو' },
        category: 'Politician',
        verified: true,
        image: 'https://picsum.photos/id/1027/200/200',
        bio: { so: 'Aasaasaha maamulka Jubbaland.', en: 'Founder of Jubaland administration.', ar: 'مؤسس إدارة جوبالاند.' },
        ratings: { fame: 78, popularity: 60 }
    },
    {
        id: 6,
        name: { so: 'Cabdicasiis Laftagareen', en: 'Abdiaziz Laftagareen', ar: 'عبد العزيز لفتاغرين' },
        role: { so: 'Madaxweynaha Koonfur Galbeed', en: 'President of South West', ar: 'رئيس الجنوب الغربي' },
        location: { so: 'Baydhabo', en: 'Baidoa', ar: 'بيدوا' },
        category: 'Politician',
        verified: true,
        image: 'https://picsum.photos/id/1062/200/200',
        bio: { so: 'Madaxweynaha dowlad goboleedka Koonfur Galbeed.', en: 'President of South West State.', ar: 'رئيس ولاية جنوب غرب الصومال.' },
        ratings: { fame: 70, popularity: 55 }
    },
    {
        id: 7,
        name: { so: 'Hormuud Telecom', en: 'Hormuud Telecom', ar: 'شركه هرمود' },
        role: { so: 'Shirkadda Isgaarsiinta', en: 'Telecom Giant', ar: 'عملاق الاتصالات' },
        location: { so: 'Muqdisho', en: 'Mogadishu', ar: 'مقديشو' },
        category: 'Business',
        verified: true,
        image: 'https://upload.wikimedia.org/wikipedia/en/2/29/Hormuud_Telecom_logo.png',
        bio: { so: 'Shirkadda ugu weyn isgaarsiinta.', en: 'Largest telecom provider.', ar: 'أكبر مزود اتصالات.' },
        services: [{ so: 'Internet', en: 'Internet', ar: 'إنترنت' }, { so: 'EVC Plus', en: 'EVC Plus', ar: 'إي في سي' }],
        ratings: { fame: 98, popularity: 90 }
    },
    {
        id: 8,
        name: { so: 'Dahabshiil Group', en: 'Dahabshiil Group', ar: 'مجموعة دهب شيل' },
        role: { so: 'Xawaalad Caalami ah', en: 'Global Remittance', ar: 'تحويل الأموال' },
        location: { so: 'Hargeysa', en: 'Hargeisa', ar: 'هرجيسا' },
        category: 'Business',
        verified: true,
        image: 'https://picsum.photos/id/1035/200/200',
        bio: { so: 'Adeegga xawaaladda ugu weyn Afrika.', en: 'Largest money transfer in Africa.', ar: 'أكبر شركة تحويل أموال في أفريقيا.' },
        services: [{ so: 'Xawaalad', en: 'Remittance', ar: 'تحويلات' }, { so: 'Bangiga', en: 'Banking', ar: 'بنوك' }],
        ratings: { fame: 95, popularity: 92 }
    },
    {
        id: 9,
        name: { so: 'Somtel', en: 'Somtel', ar: 'سومتل' },
        role: { so: 'Isgaarsiin', en: 'Telecommunications', ar: 'اتصالات' },
        location: { so: 'Hargeysa', en: 'Hargeisa', ar: 'هرجيسا' },
        category: 'Business',
        verified: true,
        image: 'https://picsum.photos/id/1042/200/200',
        bio: { so: 'Shirkad isgaarsiin oo casri ah.', en: 'Modern telecom company.', ar: 'شركة اتصالات حديثة.' },
        services: [{ so: '4G/5G', en: '4G/5G', ar: '4G/5G' }, { so: 'eDahab', en: 'eDahab', ar: 'إي دهب' }],
        ratings: { fame: 85, popularity: 80 }
    },
    {
        id: 10,
        name: { so: 'IBS Bank', en: 'IBS Bank', ar: 'بنك IBS' },
        role: { so: 'Bangiga Caalamiga', en: 'International Bank', ar: 'بنك دولي' },
        location: { so: 'Muqdisho', en: 'Mogadishu', ar: 'مقديشو' },
        category: 'Business',
        verified: true,
        image: 'https://picsum.photos/id/1050/200/200',
        bio: { so: 'Bangiga ganacsiga iyo maalgashiga.', en: 'Commercial and investment bank.', ar: 'بنك تجاري واستثماري.' },
        services: [{ so: 'Swift', en: 'Swift', ar: 'سويفت' }, { so: 'Deymo', en: 'Loans', ar: 'قروض' }],
        ratings: { fame: 75, popularity: 70 }
    },
    {
        id: 11,
        name: { so: 'Premier Bank', en: 'Premier Bank', ar: 'بنك بريمير' },
        role: { so: 'Bangiga Ganacsiga', en: 'Commercial Bank', ar: 'بنك تجاري' },
        location: { so: 'Muqdisho', en: 'Mogadishu', ar: 'مقديشو' },
        category: 'Business',
        verified: true,
        image: 'https://picsum.photos/id/1074/200/200',
        bio: { so: 'Bangiga bixiya adeegyada kaararka Mastercard.', en: 'Bank offering Mastercard services.', ar: 'بنك يقدم خدمات ماستركارد.' },
        services: [{ so: 'Mastercard', en: 'Mastercard', ar: 'ماستركارد' }, { so: 'ATM', en: 'ATM', ar: 'صراف آلي' }],
        ratings: { fame: 80, popularity: 75 }
    },
    {
        id: 12,
        name: { so: 'SomGas', en: 'SomGas', ar: 'سوم غاز' },
        role: { so: 'Shirkadda Tamarta', en: 'Energy Company', ar: 'شركة الطاقة' },
        location: { so: 'Muqdisho', en: 'Mogadishu', ar: 'مقديشو' },
        category: 'Business',
        verified: true,
        image: 'https://picsum.photos/id/1084/200/200',
        bio: { so: 'Shirkadda ugu weyn ee gaaska dabiiciga.', en: 'Major natural gas supplier.', ar: 'مورد رئيسي للغاز الطبيعي.' },
        services: [{ so: 'Gaas', en: 'Gas', ar: 'غاز' }, { so: 'Energy', en: 'Energy', ar: 'طاقة' }],
        ratings: { fame: 65, popularity: 60 }
    }
];
